version: "3"
services:
  api:
    image: jesseditson/music-identifier-api
    build: .
    volumes:
      - ".:/src/app"
    ports:
      - "8000:8000"
    command: gunicorn --reload -w 1 -b :8000 server:app
